### ISSUE TITLE
Your `Peer` type replicates `std::new::SocketAddrV4`

### ISSUE THREAD

**Issue by tov** [eecs395rust/bittorrent#4]
The definition of `Peer` at https://github.com/eecs395rust/bittorrent/blob/master/src/peer.rs is probably unnecessary, since you can use https://doc.rust-lang.org/std/net/struct.SocketAddrV4.html from the standard library. That type also supports printing and parsing.

**Comment by thehandsomepanther** [comment]
closing because peer now has more attributes: https://github.com/eecs395rust/bittorrent/blob/master/src/peer.rs#L4-L10
